# Generated by Django 5.0.4 on 2024-04-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('comments', models.CharField(max_length=30)),
                ('STARS', models.CharField(choices=[('*', '1 STAR'), ('**', '2 STAR'), ('***', '3 STAR'), ('****', '4 STAR'), ('*****', '5 STAR')], max_length=10)),
            ],
        ),
    ]
