# Generated by Django 5.0.4 on 2024-04-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
