# Generated by Django 5.0.4 on 2024-04-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='STARS',
            new_name='stars',
        ),
    ]
